#!/usr/bin/env bash
# Generate the Homebrew formula for a published release.
#
#   scripts/brew-formula.sh v0.1.0-alpha.1 > Formula/aithos.rb
#
# Generated rather than hand-edited, because a formula is four URLs and four
# checksums that must all move together on every tag. Editing that by hand is
# how a tap ends up serving one architecture from the previous release.
#
# Checksums come from the release's own SHA256SUMS, which the release workflow
# builds from each runner's output. That is convenience, not proof: what proves
# a binary is `gh attestation verify`, and the formula's header says so to
# anyone who reads it.
set -euo pipefail

TAG="${1:?usage: brew-formula.sh <tag>}"
REPO="${REPO:-aithos-protocol/registry}"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

sums=$(curl -fsSL "${BASE}/SHA256SUMS")
sum_for() {
  local target="aithos-${VERSION}-$1.tar.gz"
  local s
  s=$(printf '%s\n' "$sums" | awk -v f="$target" '$2 == f || $2 == "*"f {print $1; exit}')
  [ -n "$s" ] || { echo "no checksum for ${target} in ${BASE}/SHA256SUMS" >&2; exit 1; }
  printf '%s' "$s"
}

block() { # target, indent
  printf '%surl "%s/aithos-%s-%s.tar.gz"\n' "$2" "$BASE" "$VERSION" "$1"
  printf '%ssha256 "%s"\n' "$2" "$(sum_for "$1")"
}

cat <<RUBY
# Generated by scripts/brew-formula.sh — do not edit by hand.
#
# Homebrew is the convenient way in, not the checkable one. Before trusting a
# binary that will hold your signing keys:
#
#     gh release download --repo ${REPO} ${TAG}
#     gh attestation verify aithos-*.tar.gz --repo ${REPO}
#
class Aithos < Formula
  desc "Publish and verify signed A2A Agent Cards"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
$(block aarch64-apple-darwin '      ')
    end
    on_intel do
$(block x86_64-apple-darwin '      ')
    end
  end

  on_linux do
    on_arm do
$(block aarch64-unknown-linux-musl '      ')
    end
    on_intel do
$(block x86_64-unknown-linux-musl '      ')
    end
  end

  def install
    bin.install "aithos"
  end

  test do
    assert_match "${VERSION}", shell_output("#{bin}/aithos --version")

    # A published entry this formula does not control, verified end to end:
    # if the strict parser, the canonicalizer or the JWS profile were broken by
    # a bad build, this fails rather than passing quietly.
    system bin/"aithos", "card", "init", "--out", "card.json"
    assert_match "valid", shell_output("#{bin}/aithos card check card.json")
  end
end
RUBY
